easy_admin:
    design:
            menu:
                - { entity: 'Blog', icon: 'file' }
    entities:
      Blog:
          class: App\Entity\Blog
          title: 'Blog'
          form:
              fields:
                  - { property: 'title', label: 'Titre article', css_class: 'col-lg-6'}
                  - { property: 'author', label: 'Auteur', css_class: 'col-lg-6'}
                  - { property: 'content', label: 'Contenu article', css_class: 'col-lg-12'}
                  - { property: 'firstImageFile', type: 'vich_image', base_path: '%app.path.product_images%', label: 'Image den tete', css_class: 'col-sm-6'}
          list:
              title: "Blog"
              fields:
                  - { property: 'title', label: 'Titre article'}
                  - { property: 'author', label: 'Auteur article'}
                  - { property: 'content', label: 'Contenu de article'}