easy_admin:
    design:
            menu:
                - { entity: 'Piscines', icon: 'image' }
    entities:
      Piscines:
          class: App\Entity\Pool
          title: 'Piscines'
          form:
              fields:
                  - { type: 'group', css_class: 'col-sm-8', label: 'Informations générales', icon: 'info' }
                  - { property: 'type', label: 'Type de piscine'}
                  - { type: 'divider' }
                  - { property: 'name', label: 'Nom du spot'}
                  - { type: 'divider' }
                  - { property: 'price', label: 'Prix par personne'}
                  - { type: 'divider' }
                  - { property: 'slug', label: 'Slug'}
                  - { type: 'group', css_class: 'col-sm-4', label: 'Localisation', icon: 'map-marker'}
                  - { property: 'longitude', label: 'Longitude'}
                  - { type: 'divider' }
                  - { property: 'latitude', label: 'Latitude'}
                  - { type: 'group', css_class: 'col-sm-4', label: 'Medias', icon: 'image'}
                  - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.product_images%', label: 'Image piscine'}
                  - { type: 'group', css_class: 'col-sm-8', label: 'Equipements', icon: 'home'}
                  - { property: 'tobogan', label: 'Tobogan'}
                  - { property: 'towels', label: 'Serviettes'}
                  - { property: 'barbecue', label: 'Barbecue'}
                  - { property: 'kidsGames', label: 'Pataugeoir enfant'}
                  - { property: 'shower', label: 'Douche'}
                  - { type: 'divider' }
                  - { property: 'chair', label: 'Fauteuil transat'}
                  - { property: 'fridge', label: 'Frigo'}
                  - { property: 'heat', label: 'Chauffée'}
                  - { property: 'pingPong', label: 'Table de ping pong'}
                  - { property: 'restauration', label: 'Restauration'}
                  - { type: 'group', css_class: 'col-sm-4', label: 'Reglements', icon: 'book-open'}
                  - { property: 'pets', label: 'Animaux'}
                  - { property: 'smoke', label: 'Fumeur'}
                  - { property: 'calm', label: 'Calme'}
                  - { property: 'kids', label: 'Enfants'}
                  - { property: 'kidsFree', label: 'Gratuit pour les enfants de moins de 8 ans'}
                  - { property: 'ownerPresence', label: 'Presence des proprietaires'}
          list:
              title: "Piscine"
              fields:
                  - { property: 'type', label: 'Type de piscine'}
                  - { property: 'name', label: 'Nom du spot'}
                  - { property: 'price', label: 'Prix par personne', css_class: 'col-lg-12'}
                  - { property: 'tobogan', label: 'Tobogan'}
                  - { property: 'towels', label: 'Serviettes'}
                  - { property: 'barbecue', label: 'Barbecue'}
                  - { property: 'kidsGames', label: 'Pataugeoir enfant'}
                  - { property: 'shower', label: 'Douche'}
                  - { property: 'chair', label: 'Fauteuil transat'}
                  - { property: 'fridge', label: 'Frigo'}
                  - { property: 'heat', label: 'Chauffée'}
                  - { property: 'pingPong', label: 'Table de ping pong'}
                  - { property: 'restauration', label: 'Restauration'}
                  - { property: 'pets', label: 'Animaux'}
                  - { property: 'smoke', label: 'Fumeur'}
                  - { property: 'calm', label: 'Calme'}
                  - { property: 'kids', label: 'Enfants'}
                  - { property: 'kidsFree', label: 'Gratuit pour les enfants de moins de 8 ans'}
                  - { property: 'ownerPresence', label: 'Presence des proprietaires'}