easy_admin:
    entities:
      Pool:
          class: App\Entity\Pool
          title: 'Piscines'
          form:
              fields:
                  - { property: 'type', label: 'Type de piscine', css_class: 'col-lg-6'}
                  - { property: 'name', label: 'Nom du spot', css_class: 'col-lg-6'}
                  - { property: 'price', label: 'Prix par personne', css_class: 'col-lg-3'}
                  - { property: 'slug', label: 'Slug', css_class: 'col-lg-3'}
                  - { property: 'longitude', label: 'Longitude', css_class: 'col-lg-3'}
                  - { property: 'latitude', label: 'Latitude', css_class: 'col-lg-3'}
                  - { property: 'imageFile', type: 'vich_image', base_path: '%app.path.product_images%', label: 'Image piscine', css_class: 'col-sm-12'}
                  - { property: 'tobogan', label: 'Tobogan', css_class: 'col-lg-3'}
                  - { property: 'towels', label: 'Serviettes', css_class: 'col-lg-3'}
                  - { property: 'barbecue', label: 'Barbecue', css_class: 'col-lg-3'}
                  - { property: 'kidsGames', label: 'Pataugeoir enfant', css_class: 'col-lg-3'}
                  - { property: 'shower', label: 'Douche', css_class: 'col-lg-3'}
                  - { property: 'chair', label: 'Fauteuil transat', css_class: 'col-lg-3'}
                  - { property: 'fridge', label: 'Frigo', css_class: 'col-lg-3'}
                  - { property: 'heat', label: 'Chauffée', css_class: 'col-lg-3'}
                  - { property: 'pingPong', label: 'Table de ping pong', css_class: 'col-lg-3'}
                  - { property: 'restauration', label: 'Restauration', css_class: 'col-lg-3'}
                  - { property: 'pets', label: 'Animaux', css_class: 'col-lg-3'}
                  - { property: 'smoke', label: 'Fumeur', css_class: 'col-lg-3'}
                  - { property: 'calm', label: 'Calme', css_class: 'col-lg-3'}
                  - { property: 'kids', label: 'Enfants', css_class: 'col-lg-3'}
                  - { property: 'kidsFree', label: 'Gratuit pour les enfants de moins de 8 ans', css_class: 'col-lg-3'}
                  - { property: 'ownerPresence', label: 'Presence des proprietaires', css_class: 'col-lg-3'}
          list:
              title: "Piscine"
              fields:
                  - { property: 'type', label: 'Type de piscine', css_class: 'col-lg-6'}
                  - { property: 'name', label: 'Nom du spot', css_class: 'col-lg-6'}
                  - { property: 'price', label: 'Prix par personne', css_class: 'col-lg-12'}
                  - { property: 'tobogan', label: 'Tobogan', css_class: 'col-lg-3'}
                  - { property: 'towels', label: 'Serviettes', css_class: 'col-lg-3'}
                  - { property: 'barbecue', label: 'Barbecue', css_class: 'col-lg-3'}
                  - { property: 'kidsGames', label: 'Pataugeoir enfant', css_class: 'col-lg-3'}
                  - { property: 'shower', label: 'Douche', css_class: 'col-lg-3'}
                  - { property: 'chair', label: 'Fauteuil transat', css_class: 'col-lg-3'}
                  - { property: 'fridge', label: 'Frigo', css_class: 'col-lg-3'}
                  - { property: 'heat', label: 'Chauffée', css_class: 'col-lg-3'}
                  - { property: 'pingPong', label: 'Table de ping pong', css_class: 'col-lg-3'}
                  - { property: 'restauration', label: 'Restauration', css_class: 'col-lg-3'}
                  - { property: 'pets', label: 'Animaux', css_class: 'col-lg-3'}
                  - { property: 'smoke', label: 'Fumeur', css_class: 'col-lg-3'}
                  - { property: 'calm', label: 'Calme', css_class: 'col-lg-3'}
                  - { property: 'kids', label: 'Enfants', css_class: 'col-lg-3'}
                  - { property: 'kidsFree', label: 'Gratuit pour les enfants de moins de 8 ans', css_class: 'col-lg-3'}
                  - { property: 'ownerPresence', label: 'Presence des proprietaires', css_class: 'col-lg-3'}